name: Update README all day at 04:04

on:
  push:
  workflow_dispatch:
  schedule:
    # "At 13:37 on every day-of-week from Monday through Friday."
    - cron: '03 4 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update index.py file
        run: |
          python index.py > output.txt
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Etienne
          force: false
          signoff: false
          message: ':memo: README.md updated by Gabot'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
